// Généré automatiquement — annales DNB SVT hébergées sur Supabase Storage (bucket 'brevets').
// Régénérer via _build/scripts/make_brevets_data.py côté projet SVT_Only_v2.
export interface Brevet {
  code: string;
  annee: number;
  centre: string;
  theme: string;
  points: number;
  url: string;
  tailleKo: number;
}

export const brevets: Brevet[] = [
  { code: "25GENSCAN1", annee: 2025, centre: "Amérique du Nord", theme: "Vers de terre et agriculture", points: 25, tailleKo: 730, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25GENSCAN1_Vers_de_terre_et_agriculture.pdf" },
  { code: "25GENSCAA1", annee: 2025, centre: "Asie", theme: "Les volcans comme source d'énergie", points: 25, tailleKo: 907, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25GENSCAA1_Les_volcans_comme_source_d_energie.pdf" },
  { code: "25GENSCMEAG1", annee: 2025, centre: "Métropole", theme: "Impacts des doryphores sur les cultures de pommes de terre", points: 25, tailleKo: 1198, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25GENSCMEAG1_Impacts_des_doryphores_sur_les_cultures_de_po.pdf" },
  { code: "25GENSCPO1", annee: 2025, centre: "Polynésie", theme: "Gestion durable de la pêche aux coquilles Saint-Jacques", points: 20, tailleKo: 464, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25GENSCPO1_Gestion_durable_de_la_peche_aux_coquilles_Sai.pdf" },
  { code: "24GENSCAN1", annee: 2024, centre: "Amérique du Nord", theme: "Reconstitution d’oiseaux-éléphants de Madagascar", points: 25, tailleKo: 1114, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24GENSCAN1_Reconstitution_d_oiseaux_elephants_de_Madagas.pdf" },
  { code: "24GENSCG11", annee: 2024, centre: "Centres étrangers", theme: "Santé humaine, santé animale et préservation des écosystèmes : le cas du paludisme", points: 25, tailleKo: 1179, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24GENSCG11_Sante_humaine_sante_animale_et_preservation_d.pdf" },
  { code: "24GENSCPO1", annee: 2024, centre: "Polynésie", theme: "Le puceron : interactions entre les plantes et les pucerons", points: 25, tailleKo: 1592, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24GENSCPO1_Le_puceron_interactions_entre_les_plantes_et.pdf" },
  { code: "24GENSCPO3", annee: 2024, centre: "Polynésie (septembre)", theme: "La coquille Saint-Jacques", points: 25, tailleKo: 1013, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24GENSCPO3_La_coquille_Saint_Jacques.pdf" },
  { code: "23GENSCAN1", annee: 2023, centre: "Amérique du Nord", theme: "La culture du maïs", points: 25, tailleKo: 1172, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCAN1_La_culture_du_mais.pdf" },
  { code: "23GENSCAA1", annee: 2023, centre: "Asie", theme: "Le Chili, une région sismique", points: 25, tailleKo: 1055, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCAA1_Le_Chili_une_region_sismique.pdf" },
  { code: "23GENSCG11", annee: 2023, centre: "Centres étrangers", theme: "Le phénomène El Niño et ses conséquences sur la pêche au Pérou", points: 25, tailleKo: 1497, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCG11_Le_phenomene_El_Nino_et_ses_consequences_sur.pdf" },
  { code: "23GENSCMEAG1", annee: 2023, centre: "Métropole", theme: "Le role de l'idotee, l'abeille des mers, dans la reproduction de l'algue rouge", points: 25, tailleKo: 763, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCMEAG1_Le_role_de_l_idotee_l_abeille_des_mers_dans_l.pdf" },
  { code: "23GENSCMEAG3", annee: 2023, centre: "Métropole (septembre)", theme: "La phénylcétonurie, une maladie génétique", points: 25, tailleKo: 419, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCMEAG3_La_phenylcetonurie_une_maladie_genetique.pdf" },
  { code: "23GENSCNC1", annee: 2023, centre: "Nouvelle-Calédonie", theme: "Surpêche et comportement responsable", points: 25, tailleKo: 3168, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCNC1_Surpeche_et_comportement_responsable.pdf" },
  { code: "23GENSCPO1", annee: 2023, centre: "Polynésie", theme: "Une culture de micro-organisme pour l'alimentation humaine : la spiruline", points: 25, tailleKo: 2102, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCPO1_Une_culture_de_micro_organisme_pour_l_aliment.pdf" },
  { code: "23GENSCPO3", annee: 2023, centre: "Polynésie (septembre)", theme: "Le risque cyclonique et le dérèglement climatique", points: 23, tailleKo: 1060, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCPO3_Le_risque_cyclonique_et_le_dereglement_climat.pdf" },
  { code: "22GENSCAN1", annee: 2022, centre: "Amérique du Nord", theme: "Préparer une population face à un risque de tsunami", points: 25, tailleKo: 1524, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCAN1_Preparer_une_population_face_a_un_risque_de_t.pdf" },
  { code: "22GENSCAS1", annee: 2022, centre: "Amérique du Sud", theme: "L'évolution des populations de pins en France", points: 25, tailleKo: 1078, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCAS1_L_evolution_des_populations_de_pins_en_France.pdf" },
  { code: "22GENSCAA1", annee: 2022, centre: "Asie", theme: "La coccinelle asiatique", points: 25, tailleKo: 1216, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCAA1_La_coccinelle_asiatique.pdf" },
  { code: "22GENSCG11", annee: 2022, centre: "Centres étrangers", theme: "Le gobemouche noir et le changement climatique", points: 25, tailleKo: 2502, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCG11_Le_gobemouche_noir_et_le_changement_climatiqu.pdf" },
  { code: "22GENSCMEAG2", annee: 2022, centre: "Métropole", theme: "Les récifs coralliens : symbiose, blanchissement et services écosystémiques", points: 25, tailleKo: 1003, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCMEAG2_Les_recifs_coralliens_symbiose_blanchissement.pdf" },
  { code: "22GENSCMEAG1", annee: 2022, centre: "Métropole", theme: "Tortues marines : détermination du sexe par la température et conséquences du réchauffement climatique", points: 25, tailleKo: 983, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCMEAG1_Tortues_marines_determination_du_sexe_par_la.pdf" },
  { code: "22GENSCMEAG3", annee: 2022, centre: "Métropole (septembre)", theme: "Les moyens de prévention des IST", points: 25, tailleKo: 723, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCMEAG3_Les_moyens_de_prevention_des_IST.pdf" },
  { code: "22GENSCNC1", annee: 2022, centre: "Nouvelle-Calédonie", theme: "Les récifs coralliens et leur blanchissement", points: 25, tailleKo: 934, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCNC1_Les_recifs_coralliens_et_leur_blanchissement.pdf" },
  { code: "22GENSCPO1", annee: 2022, centre: "Polynésie", theme: "Le fonctionnement hormonal : rôle des testicules et de la testostérone", points: 25, tailleKo: 936, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCPO1_Le_fonctionnement_hormonal_role_des_testicule.pdf" },
  { code: "22GENSCPO3", annee: 2022, centre: "Polynésie (septembre)", theme: "Des insectes destructeurs de forêts (les scolytes)", points: 25, tailleKo: 1805, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCPO3_Des_insectes_destructeurs_de_forets_les_scoly.pdf" },
  { code: "21GENSCAN1", annee: 2021, centre: "Amérique du Nord", theme: "Fertilité féminine et Procréation Médicalement Assistée (PMA)", points: 25, tailleKo: 1343, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21GENSCAN1_Fertilite_feminine_et_Procreation_Medicalemen.pdf" },
  { code: "21GENSCAA1", annee: 2021, centre: "Asie", theme: "Trop de sel dans le sol sénégalais", points: 25, tailleKo: 1369, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21GENSCAA1_Trop_de_sel_dans_le_sol_senegalais.pdf" },
  { code: "21GENSCMEAG1", annee: 2021, centre: "Métropole", theme: "Pigments, photosynthèse et production d'amidon chez les plantes à feuilles rouges et panachées", points: 25, tailleKo: 1153, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21GENSCMEAG1_Pigments_photosynthese_et_production_d_amidon.pdf" },
  { code: "21GENSCMEAG3", annee: 2021, centre: "Métropole (septembre)", theme: "Un tremblement de Terre en Méditerranée (séisme du 7 juillet 2011)", points: 25, tailleKo: 5555, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21GENSCMEAG3_Un_tremblement_de_Terre_en_Mediterranee_seism.pdf" },
];
