// Généré automatiquement — annales DNB hébergées sur Supabase Storage (bucket 'brevets').
// Régénérer via scripts/make_brevets_data.py (lit scripts/brevets_manifest.csv).
export type Matiere = 'SVT' | 'Maths' | 'Français' | 'Histoire-Géo-EMC' | 'Physique-Chimie';

export interface Brevet {
  code: string;
  annee: number;
  centre: string;
  theme: string;
  points: number;
  url: string;
  tailleKo: number;
  /** Matière de l'épreuve. Absent = 'SVT' (entrées historiques). */
  matiere?: Matiere;
}

export const brevets: Brevet[] = [

  { code: "25MATAN1", annee: 2025, centre: "Amérique du Nord", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 72, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25MATAN1_Math_Mathematiques_juin.pdf" },
  { code: "25MATASN", annee: 2025, centre: "Amérique du Sud", theme: "Mathématiques · novembre", points: 100, matiere: "Maths", tailleKo: 81, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25MATASN_Math_Mathematiques_novembre.pdf" },
  { code: "25MATAA1", annee: 2025, centre: "Asie", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 89, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25MATAA1_Math_Mathematiques_juin.pdf" },
  { code: "25MATCE1", annee: 2025, centre: "Centres étrangers", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 104, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25MATCE1_Math_Mathematiques_juin.pdf" },
  { code: "25MATME1", annee: 2025, centre: "Métropole", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 73, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25MATME1_Math_Mathematiques_juin.pdf" },
  { code: "25MATME3", annee: 2025, centre: "Métropole", theme: "Mathématiques · septembre", points: 100, matiere: "Maths", tailleKo: 87, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25MATME3_Math_Mathematiques_septembre.pdf" },
  { code: "25MATNCD", annee: 2025, centre: "Nouvelle-Calédonie", theme: "Mathématiques · décembre", points: 100, matiere: "Maths", tailleKo: 71, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25MATNCD_Math_Mathematiques_decembre.pdf" },
  { code: "25MATPO1", annee: 2025, centre: "Polynésie", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 97, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25MATPO1_Math_Mathematiques_juin.pdf" },
  { code: "25MATPO3", annee: 2025, centre: "Polynésie", theme: "Mathématiques · septembre", points: 100, matiere: "Maths", tailleKo: 108, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25MATPO3_Math_Mathematiques_septembre.pdf" },
  { code: "24MATANM", annee: 2024, centre: "Amérique du Nord", theme: "Mathématiques · mai", points: 100, matiere: "Maths", tailleKo: 68, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24MATANM_Math_Mathematiques_mai.pdf" },
  { code: "24MATASD", annee: 2024, centre: "Amérique du Sud", theme: "Mathématiques · décembre", points: 100, matiere: "Maths", tailleKo: 177, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24MATASD_Math_Mathematiques_decembre.pdf" },
  { code: "24MATAA1", annee: 2024, centre: "Asie", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 79, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24MATAA1_Math_Mathematiques_juin.pdf" },
  { code: "24MATCE1", annee: 2024, centre: "Centres étrangers", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 75, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24MATCE1_Math_Mathematiques_juin.pdf" },
  { code: "24MATMT1", annee: 2024, centre: "Martinique", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 66, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24MATMT1_Math_Mathematiques_juin.pdf" },
  { code: "24MATME1", annee: 2024, centre: "Métropole", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 62, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24MATME1_Math_Mathematiques_juin.pdf" },
  { code: "24MATME3", annee: 2024, centre: "Métropole", theme: "Mathématiques · septembre", points: 100, matiere: "Maths", tailleKo: 64, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24MATME3_Math_Mathematiques_septembre.pdf" },
  { code: "24MATPO1", annee: 2024, centre: "Polynésie", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 81, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24MATPO1_Math_Mathematiques_juin.pdf" },
  { code: "24MATPO3", annee: 2024, centre: "Polynésie", theme: "Mathématiques · septembre", points: 100, matiere: "Maths", tailleKo: 89, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24MATPO3_Math_Mathematiques_septembre.pdf" },
  { code: "23MATANM", annee: 2023, centre: "Amérique du Nord", theme: "Mathématiques · mai", points: 100, matiere: "Maths", tailleKo: 60, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23MATANM_Math_Mathematiques_mai.pdf" },
  { code: "23MATASN", annee: 2023, centre: "Amérique du Sud", theme: "Mathématiques · novembre", points: 100, matiere: "Maths", tailleKo: 90, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23MATASN_Math_Mathematiques_novembre.pdf" },
  { code: "23MATAA1", annee: 2023, centre: "Asie", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 74, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23MATAA1_Math_Mathematiques_juin.pdf" },
  { code: "23MATCE1", annee: 2023, centre: "Centres étrangers", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 74, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23MATCE1_Math_Mathematiques_juin.pdf" },
  { code: "23MATME1", annee: 2023, centre: "Métropole", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 61, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23MATME1_Math_Mathematiques_juin.pdf" },
  { code: "23MATME3", annee: 2023, centre: "Métropole", theme: "Mathématiques · septembre", points: 100, matiere: "Maths", tailleKo: 75, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23MATME3_Math_Mathematiques_septembre.pdf" },
  { code: "23MATNCD", annee: 2023, centre: "Nouvelle-Calédonie", theme: "Mathématiques · décembre", points: 100, matiere: "Maths", tailleKo: 84, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23MATNCD_Math_Mathematiques_decembre.pdf" },
  { code: "23MATPO1", annee: 2023, centre: "Polynésie", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 118, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23MATPO1_Math_Mathematiques_juin.pdf" },
  { code: "23MATPO3", annee: 2023, centre: "Polynésie", theme: "Mathématiques · septembre", points: 100, matiere: "Maths", tailleKo: 176, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23MATPO3_Math_Mathematiques_septembre.pdf" },
  { code: "22MATAN1", annee: 2022, centre: "Amérique du Nord", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 76, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22MATAN1_Math_Mathematiques_juin.pdf" },
  { code: "22MATASN", annee: 2022, centre: "Amérique du Sud", theme: "Mathématiques · novembre", points: 100, matiere: "Maths", tailleKo: 81, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22MATASN_Math_Mathematiques_novembre.pdf" },
  { code: "22MATAA1", annee: 2022, centre: "Asie", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 273, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22MATAA1_Math_Mathematiques_juin.pdf" },
  { code: "22MATCE1", annee: 2022, centre: "Centres étrangers", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 75, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22MATCE1_Math_Mathematiques_juin.pdf" },
  { code: "22MATME1", annee: 2022, centre: "Métropole", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 270, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22MATME1_Math_Mathematiques_juin.pdf" },
  { code: "22MATME3", annee: 2022, centre: "Métropole", theme: "Mathématiques · septembre", points: 100, matiere: "Maths", tailleKo: 59, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22MATME3_Math_Mathematiques_septembre.pdf" },
  { code: "22MATMS1", annee: 2022, centre: "Métropole (secours)", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 58, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22MATMS1_Math_Mathematiques_juin.pdf" },
  { code: "22MATNCD", annee: 2022, centre: "Nouvelle-Calédonie", theme: "Mathématiques · décembre", points: 100, matiere: "Maths", tailleKo: 60, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22MATNCD_Math_Mathematiques_decembre.pdf" },
  { code: "22MATPO1", annee: 2022, centre: "Polynésie", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 319, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22MATPO1_Math_Mathematiques_juin.pdf" },
  { code: "22MATPO3", annee: 2022, centre: "Polynésie", theme: "Mathématiques · septembre", points: 100, matiere: "Maths", tailleKo: 93, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22MATPO3_Math_Mathematiques_septembre.pdf" },
  { code: "21MATAN1", annee: 2021, centre: "Amérique du Nord", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 53, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21MATAN1_Math_Mathematiques_juin.pdf" },
  { code: "21MATASN", annee: 2021, centre: "Amérique du Sud", theme: "Mathématiques · novembre", points: 100, matiere: "Maths", tailleKo: 71, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21MATASN_Math_Mathematiques_novembre.pdf" },
  { code: "21MATAA1", annee: 2021, centre: "Asie", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 61, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21MATAA1_Math_Mathematiques_juin.pdf" },
  { code: "21MATAS21", annee: 2021, centre: "Asie (secours)", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 63, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21MATAS21_Math_Mathematiques_juin.pdf" },
  { code: "21MATCE1", annee: 2021, centre: "Centres étrangers", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 68, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21MATCE1_Math_Mathematiques_juin.pdf" },
  { code: "21MATME1", annee: 2021, centre: "Métropole", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 65, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21MATME1_Math_Mathematiques_juin.pdf" },
  { code: "21MATME3", annee: 2021, centre: "Métropole", theme: "Mathématiques · septembre", points: 100, matiere: "Maths", tailleKo: 171, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21MATME3_Math_Mathematiques_septembre.pdf" },
  { code: "21MATNCD", annee: 2021, centre: "Nouvelle-Calédonie", theme: "Mathématiques · décembre", points: 100, matiere: "Maths", tailleKo: 67, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21MATNCD_Math_Mathematiques_decembre.pdf" },
  { code: "21MATPO1", annee: 2021, centre: "Polynésie", theme: "Mathématiques · juin", points: 100, matiere: "Maths", tailleKo: 175, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21MATPO1_Math_Mathematiques_juin.pdf" },
  { code: "25GENSCAN1", annee: 2025, centre: "Amérique du Nord", theme: "Vers de terre et agriculture", points: 25, matiere: "SVT", tailleKo: 730, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25GENSCAN1_Vers_de_terre_et_agriculture.pdf" },
  { code: "25GENSCAA1", annee: 2025, centre: "Asie", theme: "Les volcans comme source d'énergie", points: 25, matiere: "SVT", tailleKo: 907, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25GENSCAA1_Les_volcans_comme_source_d_energie.pdf" },
  { code: "25GENSCMEAG1", annee: 2025, centre: "Métropole", theme: "Impacts des doryphores sur les cultures de pommes de terre", points: 25, matiere: "SVT", tailleKo: 1198, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25GENSCMEAG1_Impacts_des_doryphores_sur_les_cultures_de_po.pdf" },
  { code: "25GENSCPO1", annee: 2025, centre: "Polynésie", theme: "Gestion durable de la pêche aux coquilles Saint-Jacques", points: 20, matiere: "SVT", tailleKo: 464, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/25GENSCPO1_Gestion_durable_de_la_peche_aux_coquilles_Sai.pdf" },
  { code: "24GENSCAN1", annee: 2024, centre: "Amérique du Nord", theme: "Reconstitution d’oiseaux-éléphants de Madagascar", points: 25, matiere: "SVT", tailleKo: 1114, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24GENSCAN1_Reconstitution_d_oiseaux_elephants_de_Madagas.pdf" },
  { code: "24GENSCG11", annee: 2024, centre: "Centres étrangers", theme: "Santé humaine, santé animale et préservation des écosystèmes : le cas du paludisme", points: 25, matiere: "SVT", tailleKo: 1179, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24GENSCG11_Sante_humaine_sante_animale_et_preservation_d.pdf" },
  { code: "24GENSCPO1", annee: 2024, centre: "Polynésie", theme: "Le puceron : interactions entre les plantes et les pucerons", points: 25, matiere: "SVT", tailleKo: 1592, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24GENSCPO1_Le_puceron_interactions_entre_les_plantes_et.pdf" },
  { code: "24GENSCPO3", annee: 2024, centre: "Polynésie (septembre)", theme: "La coquille Saint-Jacques", points: 25, matiere: "SVT", tailleKo: 1013, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/24GENSCPO3_La_coquille_Saint_Jacques.pdf" },
  { code: "23GENSCAN1", annee: 2023, centre: "Amérique du Nord", theme: "La culture du maïs", points: 25, matiere: "SVT", tailleKo: 1172, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCAN1_La_culture_du_mais.pdf" },
  { code: "23GENSCAA1", annee: 2023, centre: "Asie", theme: "Le Chili, une région sismique", points: 25, matiere: "SVT", tailleKo: 1055, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCAA1_Le_Chili_une_region_sismique.pdf" },
  { code: "23GENSCG11", annee: 2023, centre: "Centres étrangers", theme: "Le phénomène El Niño et ses conséquences sur la pêche au Pérou", points: 25, matiere: "SVT", tailleKo: 1497, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCG11_Le_phenomene_El_Nino_et_ses_consequences_sur.pdf" },
  { code: "23GENSCMEAG1", annee: 2023, centre: "Métropole", theme: "Le role de l'idotee, l'abeille des mers, dans la reproduction de l'algue rouge", points: 25, matiere: "SVT", tailleKo: 763, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCMEAG1_Le_role_de_l_idotee_l_abeille_des_mers_dans_l.pdf" },
  { code: "23GENSCMEAG3", annee: 2023, centre: "Métropole (septembre)", theme: "La phénylcétonurie, une maladie génétique", points: 25, matiere: "SVT", tailleKo: 419, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCMEAG3_La_phenylcetonurie_une_maladie_genetique.pdf" },
  { code: "23GENSCNC1", annee: 2023, centre: "Nouvelle-Calédonie", theme: "Surpêche et comportement responsable", points: 25, matiere: "SVT", tailleKo: 3168, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCNC1_Surpeche_et_comportement_responsable.pdf" },
  { code: "23GENSCPO1", annee: 2023, centre: "Polynésie", theme: "Une culture de micro-organisme pour l'alimentation humaine : la spiruline", points: 25, matiere: "SVT", tailleKo: 2102, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCPO1_Une_culture_de_micro_organisme_pour_l_aliment.pdf" },
  { code: "23GENSCPO3", annee: 2023, centre: "Polynésie (septembre)", theme: "Le risque cyclonique et le dérèglement climatique", points: 23, matiere: "SVT", tailleKo: 1060, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/23GENSCPO3_Le_risque_cyclonique_et_le_dereglement_climat.pdf" },
  { code: "22GENSCAN1", annee: 2022, centre: "Amérique du Nord", theme: "Préparer une population face à un risque de tsunami", points: 25, matiere: "SVT", tailleKo: 1524, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCAN1_Preparer_une_population_face_a_un_risque_de_t.pdf" },
  { code: "22GENSCAS1", annee: 2022, centre: "Amérique du Sud", theme: "L'évolution des populations de pins en France", points: 25, matiere: "SVT", tailleKo: 1078, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCAS1_L_evolution_des_populations_de_pins_en_France.pdf" },
  { code: "22GENSCAA1", annee: 2022, centre: "Asie", theme: "La coccinelle asiatique", points: 25, matiere: "SVT", tailleKo: 1216, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCAA1_La_coccinelle_asiatique.pdf" },
  { code: "22GENSCG11", annee: 2022, centre: "Centres étrangers", theme: "Le gobemouche noir et le changement climatique", points: 25, matiere: "SVT", tailleKo: 2502, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCG11_Le_gobemouche_noir_et_le_changement_climatiqu.pdf" },
  { code: "22GENSCMEAG2", annee: 2022, centre: "Métropole", theme: "Les récifs coralliens : symbiose, blanchissement et services écosystémiques", points: 25, matiere: "SVT", tailleKo: 1003, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCMEAG2_Les_recifs_coralliens_symbiose_blanchissement.pdf" },
  { code: "22GENSCMEAG1", annee: 2022, centre: "Métropole", theme: "Tortues marines : détermination du sexe par la température et conséquences du réchauffement climatique", points: 25, matiere: "SVT", tailleKo: 983, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCMEAG1_Tortues_marines_determination_du_sexe_par_la.pdf" },
  { code: "22GENSCMEAG3", annee: 2022, centre: "Métropole (septembre)", theme: "Les moyens de prévention des IST", points: 25, matiere: "SVT", tailleKo: 723, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCMEAG3_Les_moyens_de_prevention_des_IST.pdf" },
  { code: "22GENSCNC1", annee: 2022, centre: "Nouvelle-Calédonie", theme: "Les récifs coralliens et leur blanchissement", points: 25, matiere: "SVT", tailleKo: 934, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCNC1_Les_recifs_coralliens_et_leur_blanchissement.pdf" },
  { code: "22GENSCPO1", annee: 2022, centre: "Polynésie", theme: "Le fonctionnement hormonal : rôle des testicules et de la testostérone", points: 25, matiere: "SVT", tailleKo: 936, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCPO1_Le_fonctionnement_hormonal_role_des_testicule.pdf" },
  { code: "22GENSCPO3", annee: 2022, centre: "Polynésie (septembre)", theme: "Des insectes destructeurs de forêts (les scolytes)", points: 25, matiere: "SVT", tailleKo: 1805, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/22GENSCPO3_Des_insectes_destructeurs_de_forets_les_scoly.pdf" },
  { code: "21GENSCAN1", annee: 2021, centre: "Amérique du Nord", theme: "Fertilité féminine et Procréation Médicalement Assistée (PMA)", points: 25, matiere: "SVT", tailleKo: 1343, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21GENSCAN1_Fertilite_feminine_et_Procreation_Medicalemen.pdf" },
  { code: "21GENSCAA1", annee: 2021, centre: "Asie", theme: "Trop de sel dans le sol sénégalais", points: 25, matiere: "SVT", tailleKo: 1369, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21GENSCAA1_Trop_de_sel_dans_le_sol_senegalais.pdf" },
  { code: "21GENSCMEAG1", annee: 2021, centre: "Métropole", theme: "Pigments, photosynthèse et production d'amidon chez les plantes à feuilles rouges et panachées", points: 25, matiere: "SVT", tailleKo: 1153, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21GENSCMEAG1_Pigments_photosynthese_et_production_d_amidon.pdf" },
  { code: "21GENSCMEAG3", annee: 2021, centre: "Métropole (septembre)", theme: "Un tremblement de Terre en Méditerranée (séisme du 7 juillet 2011)", points: 25, matiere: "SVT", tailleKo: 5555, url: "https://djodkjysovalpufgevrr.supabase.co/storage/v1/object/public/brevets/21GENSCMEAG3_Un_tremblement_de_Terre_en_Mediterranee_seism.pdf" },
];
